version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './app/:/var/www/html'
#    env_file:
#      - .env
#    user: 1000:1000